name: yesblog
version: 0.0.1
build-type: Simple

flags:
  dev:
    description: Turn on development settings, like auto-reload templates.
    default: false
    manual: false
  library-only:
    description: Build for use with "yesod devel"
    default: false
    manual: false

library:
  source-dirs: src
  ghc-options: -Wall -fwarn-tabs -O2
  when:
    - condition: flag(dev) || flag(library-only)
      cpp-options: -DDEVELOPMENT
      ghc-options: -O0
  dependencies:
    - base >=4.20.0 && <4.22
    - yesod >=1.6.0 && <1.7
    - yesod-core >=1.6.0 && <1.7
    - yesod-auth >=1.6.0 && <1.7
    - yesod-auth-hashdb >=1.7.1 && <1.8
    - yesod-static >=1.6.0 && <1.7
    - yesod-form >=1.7.0 && <1.8
    - yesod-markdown
    - yesod-persistent >=1.6.0 && <1.7
    - classy-prelude >=1.5.0 && <1.6
    - classy-prelude-conduit >=1.5.0 && <1.6
    - classy-prelude-yesod >=1.5.0 && <1.6
    - bytestring >=0.12.2 && <0.13
    - text >=2.1.3 && <2.2
    - persistent >=2.17.1 && <2.18
    - persistent-postgresql >=2.13.7 && <2.14
    - persistent-sqlite >=2.13.3 && <2.14
    - persistent-template >=2.12.0 && <2.13
    - persistent-pagination >=0.1.0 && <0.2
    - template-haskell
    - shakespeare >=2.1.0 && <2.2
    - hjsmin >=0.2.1 && <0.3
    - monad-control >=1.0.3 && <1.1
    - wai-extra >=3.1.18 && <3.2
    - yaml >=0.11.11 && <0.12
    - http-conduit >=2.3.9 && <2.4
    - yesod-auth-oauth2 >=0.7.4.0 && <0.8
    - yesod-newsfeed
    - uri-bytestring >=0.4.0.1 && <0.5
    - directory >=1.3.8 && <1.4
    - warp >=3.4.9 && <3.5
    - data-default
    - aeson >=2.2.3 && <2.3
    - blaze-markup >=0.8.3 && <0.9
    - bcrypt >=0.0.11 && <0.1
    - conduit >=1.3.6 && <1.4
    - monad-logger >=0.3.40 && <0.4
    - fast-logger >=3.2.6 && <3.3
    - wai-logger >=2.5.0 && <2.6
    - file-embed
    - filepath
    - safe
    - unordered-containers
    - containers
    - vector
    - time
    - bcrypt >=0.0.11 && <0.1
    - uuid
    - process
    - case-insensitive
    - http-client-tls
    - wai

executables:
  yesblog:
    main: main.hs
    source-dirs: app
    dependencies:
      - base
      - yesblog
      - foreign-store >=0.2 && <0.3
      - warp >=3.4.9 && <3.5
    ghc-options: -threaded -O2 -rtsopts -with-rtsopts=-N
    when:
      - condition: flag(library-only)
        buildable: false

tests:
  test:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options: -Wall
    dependencies:
      - base
      - hkforum
      - yesod-test
      - yesod-core
      - yesod
      - persistent
      - persistent-sqlite
      - resourcet
      - monad-logger
      - shakespeare
      - transformers
      - hspec
      - classy-prelude
      - classy-prelude-yesod
